from typing import Any

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class EssayReview(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """An AI-powered admissions essay review.

    Stores the submitted text, user and target university/program context,
    and the structured evaluation generated by the LLM service.
    """

    __tablename__ = "essay_reviews"

    user_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    university_id: Mapped[str | None] = mapped_column(
        ForeignKey("universities.id"), nullable=True, index=True
    )
    program_id: Mapped[str | None] = mapped_column(String, nullable=True)

    title: Mapped[str] = mapped_column(String, nullable=False, default="Untitled Essay")
    prompt_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    word_count: Mapped[int] = mapped_column(Integer, nullable=False)
    essay_snippet: Mapped[str] = mapped_column(String(300), nullable=False)
    essay_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Full structured EssayAnalysisResult schema serialized into JSONB
    analysis_result: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)

    # Extracted overall score (0-100) for fast indexing and ordering
    overall_score: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
