"""add act, ent, dream university fields

Revision ID: 37ab0712a3b3
Revises: 642d57dd1c4c
Create Date: 2026-07-21 21:08:51.837777

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '37ab0712a3b3'
down_revision: str | None = '642d57dd1c4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('act_score', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('ent_score', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('dream_university_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'dream_university_id')
    op.drop_column('student_profiles', 'ent_score')
    op.drop_column('student_profiles', 'act_score')
    # ### end Alembic commands ###
