"""add student profile and achievements tables

Revision ID: 642d57dd1c4c
Revises: 3bc8f0f04260
Create Date: 2026-07-21 20:00:04.370347

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '642d57dd1c4c'
down_revision: str | None = '3bc8f0f04260'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('achieved', sa.Boolean(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_achievements_user_id_key')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('sat_score', sa.Integer(), nullable=True),
    sa.Column('ielts_score', sa.Float(), nullable=True),
    sa.Column('toefl_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
