"""add universities table

Revision ID: b93a8e5a8110
Revises: 37ab0712a3b3
Create Date: 2026-07-21 21:50:06.964333

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b93a8e5a8110'
down_revision: str | None = '37ab0712a3b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('logo_initials', sa.String(), nullable=False),
    sa.Column('world_ranking', sa.Integer(), nullable=False),
    sa.Column('national_ranking', sa.Integer(), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('selectivity_level', sa.String(), nullable=False),
    sa.Column('min_gpa', sa.Float(), nullable=False),
    sa.Column('sat_low', sa.Integer(), nullable=False),
    sa.Column('sat_high', sa.Integer(), nullable=False),
    sa.Column('act_min', sa.Integer(), nullable=True),
    sa.Column('act_max', sa.Integer(), nullable=True),
    sa.Column('ielts_min', sa.Float(), nullable=False),
    sa.Column('toefl_min', sa.Integer(), nullable=False),
    sa.Column('tuition_per_year_usd', sa.Integer(), nullable=False),
    sa.Column('living_cost_per_year_usd', sa.Integer(), nullable=False),
    sa.Column('scholarship_available', sa.Boolean(), nullable=False),
    sa.Column('scholarship_coverage', sa.String(), nullable=False),
    sa.Column('application_deadline', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accept_rate_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gradient_from', sa.String(), nullable=False),
    sa.Column('gradient_to', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_country'), 'universities', ['country'], unique=False)
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.drop_index(op.f('ix_universities_country'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
