import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from app.schemas.base import BaseSchema


class CategoryScores(BaseModel):
    structure: int = Field(ge=0, le=100, description="Organization, paragraph transitions, logical pacing")
    storytelling: int = Field(ge=0, le=100, description="Narrative arc, emotional resonance, show vs tell")
    voice_and_authenticity: int = Field(ge=0, le=100, description="Uniqueness, distinct personal voice, honesty")
    clarity_and_flow: int = Field(ge=0, le=100, description="Readability, conciseness, cadence, vocabulary")
    grammar_and_mechanics: int = Field(ge=0, le=100, description="Grammar, punctuation, syntax, style precision")


class ClicheItem(BaseModel):
    quote: str = Field(description="Exact phrase or sentence exhibiting the cliché")
    issue: str = Field(description="Why this phrase is considered generic, overused, or ineffective")
    replacement_idea: str = Field(description="Actionable suggestion to express the thought more authentically")


class PromptAlignment(BaseModel):
    score: int = Field(ge=0, le=100, description="Adherence to prompt requirements (0-100)")
    assessment: str = Field(description="Qualitative review of how well the prompt was answered")
    missing_elements: list[str] = Field(default_factory=list, description="Specific aspects of the prompt not adequately addressed")


class UniversityAlignment(BaseModel):
    score: int = Field(ge=0, le=100, description="Alignment with the university culture, values, and strengths (0-100)")
    assessment: str = Field(description="Qualitative review of university fit in the essay")
    aligned_values: list[str] = Field(default_factory=list, description="University core values successfully demonstrated")


class ActionableRecommendation(BaseModel):
    priority: Literal["high", "medium", "low"] = Field(description="Priority of the recommendation")
    category: str = Field(description="Category, e.g. 'Hook & Intro', 'Conclusion', 'Show vs Tell', 'Voice'")
    advice: str = Field(description="Concrete critique and actionable instruction")
    example_improvement: str | None = Field(default=None, description="Illustrative before/after or revised phrasing idea")


class EssayAnalysisResult(BaseModel):
    """The structured analysis generated by the AI Essay Reviewer engine."""

    overall_score: int = Field(ge=0, le=100, description="Overall essay quality score (0-100)")
    headline_verdict: str = Field(description="Concise 1-2 sentence executive summary of the essay's impact")
    category_scores: CategoryScores
    strengths: list[str] = Field(description="Key strengths and effective elements of the essay")
    weaknesses: list[str] = Field(description="Core areas needing revision or development")
    cliches_detected: list[ClicheItem] = Field(default_factory=list, description="Clichés and generic tropes identified")
    prompt_alignment: PromptAlignment
    university_alignment: UniversityAlignment
    actionable_recommendations: list[ActionableRecommendation] = Field(
        description="Prioritized, step-by-step revision guidance"
    )
    suggested_next_steps: list[str] = Field(
        description="Immediate 3-4 next steps for the student to revise this draft"
    )


class EssayAnalyzeRequest(BaseModel):
    """Request payload sent by the frontend to trigger essay analysis."""

    title: str = Field(default="Untitled Essay", max_length=200)
    essay_text: str = Field(min_length=150, max_length=25000, description="The essay content to analyze")
    university_id: str | None = Field(default=None, description="Optional target university ID (e.g. uni-mit)")
    program_id: str | None = Field(default=None, description="Optional target program/major ID")
    prompt_text: str | None = Field(default=None, max_length=2000, description="The essay prompt or question")
    include_profile_context: bool = Field(
        default=True, description="Whether to safely pass anonymized student profile context for better personalization"
    )


class EssayReviewRead(BaseSchema):
    """Full essay review returned when reading or completing an analysis."""

    id: uuid.UUID
    user_id: str
    university_id: str | None
    program_id: str | None
    title: str
    prompt_text: str | None
    word_count: int
    essay_snippet: str
    essay_text: str
    analysis_result: EssayAnalysisResult
    overall_score: int
    created_at: datetime
    updated_at: datetime


class EssayReviewSummaryRead(BaseSchema):
    """Compact summary of an essay review for list/history views."""

    id: uuid.UUID
    university_id: str | None
    program_id: str | None
    title: str
    prompt_text: str | None
    word_count: int
    essay_snippet: str
    overall_score: int
    created_at: datetime
